### PR TITLE
Merge refactored code into master

### PR DESCRIPTION
**Pull request by banksio**
The entire remote-media codebase has been refactored in conjunction with the development of v1.0.0.

This branch includes a slew of changes, both major and minor:

- `server.js` refactored into `socketTransmit.js`, `handlers.js` and the `Room` object.
- Video duration and video completion events are now handled server-side rather than client-side, which should lead to more reliable queue autoplay.
- New clients sync to existing clients when a video is already playing as a client joins. (#3)
- Clients can choose to push a new timestamp to other clients if they seek along the video. (#18)
- Clients can now set nicknames for a more meaningful client table in the admin panel.
- Both the client and admin panel now have connection status indicators, among other UI improvements. (#8)
- Testing is being implemented. (#17)

Some smaller changes are not mentioned here.

### CODE REVIEW

**Comment by Mattsio** [comment]
Sorry this unacceptable, one out of the two tests failed. Get your house in order

**Review by Mattsio — CHANGES_REQUESTED** [review]
Please fix your garbage pipelines. Get your house in order. Real programmers don't make mistakes

**Comment by banksio** [comment]
> Please fix your garbage pipelines. Get your house in order. Real programmers don't make mistakes

Apologies @Mattsio, these tests were for deprecated code. I've cleaned up these tests and removed the deprecated code.

**Review by Mattsio — APPROVED** [review]
Thank you kindly for amending your code and making your spaghetti pipelines work. Good job, seriously.

**Pull request merged**
